package com.raz.gddtwitter.service

object StopWords {
  val stopWords: Set[String] = Set(
      "rt", "a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all",
      "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "amongst",
      "amoungst", "amount",  "an", "and", "another", "any", "anyhow", "anyone", "anything", "anyway",
      "anywhere", "are", "around", "as",  "at", "back", "be", "became", "because", "become", "becomes",
      "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides",
      "between", "beyond", "bill", "both", "bottom", "but", "by", "call", "can", "cannot", "cant", "co",
      "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due",
      "during", "each", "eg", "eight", "either", "eleven", "else", "elsewhere", "empty", "enough",
      "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few",
      "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly",
      "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had",
      "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein",
      "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "i", "ie",
      "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last",
      "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might",
      "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself",
      "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none",
      "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one",
      "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over",
      "own", "part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed",
      "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere",
      "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes",
      "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them",
      "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein",
      "thereupon", "these", "they", "thick", "thin", "third", "this", "those", "though", "three",
      "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards",
      "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we",
      "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter",
      "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
      "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would",
      "yet", "you", "your", "yours", "yourself", "yourselves", "the",
      //Nederlander stop worden
      "aan", "aangaande", "aangezien", "achter", "achterna", "af", "afgelopen", "al", "aldaar", "aldus", "alhoewel",
      "alias", "alle", "allebei", "alleen", "als", "alsnog", "altijd", "altoos", "ander", "andere", "anders", "anderszins", "behalve",
      "behoudens", "beide", "beiden", "ben", "beneden", "bent", "bepaald", "betreffende", "bij", "binnen", "binnenin", "boven", "bovenal",
      "bovendien", "bovengenoemd", "bovenstaand", "bovenvermeld", "buiten", "daar", "daarheen", "daarin", "daarna", "daarnet", "daarom",
      "daarop", "daarvanlangs", "dan", "dat", "de", "die", "dikwijls", "dit", "door", "doorgaand", "dus", "echter", "een", "eer", "eerdat",
      "eerder", "eerlang", "eerst", "elk", "elke", "en", "enig", "enigszins", "enkel", "er", "erdoor", "even", "eveneens", "evenwel",
      "gauw", "gedurende", "geen", "gehad", "gekund", "geleden", "gelijk", "gemoeten", "gemogen", "geweest", "gewoon", "gewoonweg",
      "haar", "had", "hadden", "hare", "heb", "hebben", "hebt", "heeft", "hem", "hen", "het", "hierbeneden", "hierboven", "hij", "hoe",
      "hoewel", "hun", "hunne", "ik", "ikzelf", "in", "inmiddels", "inzake", "is", "je", "jezelf", "jij", "jijzelf", "jou", "jouw",
      "jouwe", "juist", "jullie", "kan", "klaar", "kon", "konden", "krachtens", "kunnen", "kunt", "later", "liever", "maar", "mag",
      "me", "meer", "men", "met", "mezelf", "mij", "mijn", "mijnent", "mijner", "mijzelf", "misschien", "mocht", "mochten", "moest",
      "moesten", "moet", "moeten", "mogen", "na", "naar", "nadat", "net", "niet", "noch", "nog", "nogal", "nu", "of", "ofschoon", "om",
      "omdat", "omhoog", "omlaag", "omstreeks", "omtrent", "omver", "onder", "ondertussen", "ongeveer", "ons", "onszelf", "onze", "ook",
      "op", "opnieuw", "opzij", "over", "overeind", "overigens", "pas", "precies", "reeds", "rond", "rondom", "sedert", "sinds", "sindsdien",
      "slechts", "sommige", "spoedig", "steeds", "tamelijk", "te", "tenzij", "terwijl", "thans", "tijdens", "toch", "toen", "toenmaals",
      "toenmalig", "tot", "totdat", "tussen", "uit", "uitgezonderd", "vaakwat", "van", "vandaan", "vanuit", "vanwege", "veeleer", "verder",
      "vervolgens", "vol", "volgens", "voor", "vooraf", "vooral", "vooralsnog", "voorbij", "voordat", "voordezen", "voordien", "voorheen",
      "voorop", "vooruit", "vrij", "vroeg", "waar", "waarom", "wanneer", "want", "waren", "was", "wat", "we", "weer", "weg", "wegens", "wel",
      "weldra", "welk", "welke", "wie", "wiens", "wier", "wij", "wijzelf", "zal", "ze", "zei", "zelfs", "zichzelf", "zij", "zijn", "zijne", "zo",
      "zodra", "zonder", "zou", "zouden", "zowat", "zulke", "zullen", "zult", "u"
    )
}
